#!/bin/bash

# Domain
DOMAIN=$1 # Domain name (e.g. example.com)
WWW_PATH="/var/www" # All domain folders are stored here with their config. DO NOT change this.
DOMAIN_PATH="$WWW_PATH/$DOMAIN" # Domain folder
PUBLIC_PATH="$DOMAIN_PATH/public" # Public folder for www
ENV_FILE="$DOMAIN_PATH/.env" # Environment file for domain

# Logs
LOGS_PATH="$DOMAIN_PATH/logs" # Logs folder
LOGS_PATH_ACCESS="$LOGS_PATH/access.log" # Access log
LOGS_PATH_ERROR="$LOGS_PATH/error.log" # Error log

# Deployment
DEPLOY_PATH="$DOMAIN_PATH/deploy" # Deploy folder for deployment scripts
FLAGS_PATH="$DEPLOY_PATH/flags" # Flags folder for deployment scripts
FLAGS_WEBONLY_PATH="$DEPLOY_PATH/flags/web" # Flags folder for Apache to use for setting flags
ARTIFACTS_PATH="$DEPLOY_PATH/artifacts" # Artifacts folder for deployment scripts that are used for copying over
ARTIFACTS_WEB_PATH="$DEPLOY_PATH/artifacts/web" # Artifacts folder for deployment scripts that are used for copying over web-only resources

# Apache
VHOST_EXAMPLE_FILE="002-EXAMPLE.COM.conf"
VHOST_DOMAIN_FILE="002-$DOMAIN.conf"
VHOST_DOMAIN_LETSENCRYPT_FILE="002-$DOMAIN-le-ssl.conf" # DO NOT modify part "le-ssl.conf"
VHOST_DOMAIN_SELFCERT_FILE="002-$DOMAIN-selfsigned.conf"

APACHE_AVAILABLE_PATH="/etc/apache2/sites-available"
APACHE_ENABLED_PATH="/etc/apache2/sites-enabled"

VHOST_AVAILABLE_EXAMPLE_FILE_PATH="$APACHE_AVAILABLE_PATH/$VHOST_EXAMPLE_FILE"
VHOST_AVAILABLE_DOMAIN_FILE_PATH="$APACHE_AVAILABLE_PATH/$VHOST_DOMAIN_FILE"
VHOST_AVAILABLE_DOMAIN_LETSENCRYPT_FILE_PATH="$APACHE_AVAILABLE_PATH/$VHOST_DOMAIN_LETSENCRYPT_FILE"
VHOST_AVAILABLE_DOMAIN_SELFCERT_FILE_PATH="$APACHE_AVAILABLE_PATH/$VHOST_DOMAIN_SELFCERT_FILE"

VHOST_ENABLED_EXAMPLE_FILE_PATH="$APACHE_ENABLED_PATH/$VHOST_EXAMPLE_FILE"
VHOST_ENABLED_DOMAIN_FILE_PATH="$APACHE_ENABLED_PATH/$VHOST_DOMAIN_FILE"
VHOST_ENABLED_DOMAIN_LETSENCRYPT_FILE_PATH="$APACHE_ENABLED_PATH/$VHOST_DOMAIN_LETSENCRYPT_FILE"
VHOST_ENABLED_DOMAIN_SELFCERT_FILE_PATH="$APACHE_ENABLED_PATH/$VHOST_DOMAIN_SELFCERT_FILE"

# PHP
PHP_VERSION=$(php -r "echo PHP_VERSION;" | cut -d'.' -f1,2) # Get PHP version
PHP_CLI_CONFIG_PATH="/etc/php/$PHP_VERSION/cli/conf.d" # PHP CLI config path
PHP_CLI_CUSTOM_INI_FILE="99-custom.ini" # PHP CLI ini file
PHP_CLI_CUSTOM_INI_PATH="$PHP_CLI_CONFIG_PATH/$PHP_CLI_CUSTOM_INI_FILE" # Custom PHP ini file for CLI

# SSL
LETSENCRYPT_PATH="/etc/letsencrypt/live" # Live SSL path for Let's Encrypt. DO NOT modify.
LETSENCRYPT_DOMAIN_PATH="$LETSENCRYPT_PATH/$DOMAIN" # DO NOT modify.

SELFCERT_PATH="/etc/ssl" # Self-signed SSL path
SELFCERT_DOMAIN_PATH="$SELFCERT_PATH/$DOMAIN"

# CRON
CRON_BLUEGREEN_DEPLOY_FILE="/etc/cron.d/${DOMAIN}__blue-green-deploy" # Cron file for blue-green deployment via webhook

# Ensure DOMAIN is set
if [[ -z "$DOMAIN" ]]; then
    echo "🟥 DOMAIN is not set. Aborting."
    exit 1
fi

# Create initial domains dir
echo -e "\n 🟩  Creating initial domain folder"
mkdir -p "$DOMAIN_PATH"

# Save paths to .env file
cat > "$ENV_FILE" <<EOF
DOMAIN="$DOMAIN"
WWW_PATH="$WWW_PATH"
DOMAIN_PATH="$DOMAIN_PATH"
PUBLIC_PATH="$PUBLIC_PATH"

LOGS_PATH="$LOGS_PATH"
LOGS_PATH_ACCESS="$LOGS_PATH_ACCESS"
LOGS_PATH_ERROR="$LOGS_PATH_ERROR"

DEPLOY_PATH="$DEPLOY_PATH"
FLAGS_PATH="$FLAGS_PATH"
FLAGS_WEBONLY_PATH="$FLAGS_WEBONLY_PATH"
ARTIFACTS_PATH="$ARTIFACTS_PATH"
ARTIFACTS_WEB_PATH="$ARTIFACTS_WEB_PATH"

APACHE_AVAILABLE_PATH="$APACHE_AVAILABLE_PATH"
APACHE_ENABLED_PATH="$APACHE_ENABLED_PATH"

VHOST_EXAMPLE_FILE="$VHOST_EXAMPLE_FILE"
VHOST_DOMAIN_FILE="$VHOST_DOMAIN_FILE"
VHOST_DOMAIN_LETSENCRYPT_FILE="$VHOST_DOMAIN_LETSENCRYPT_FILE"
VHOST_DOMAIN_SELFCERT_FILE="$VHOST_DOMAIN_SELFCERT_FILE"
VHOST_AVAILABLE_EXAMPLE_FILE_PATH="$VHOST_AVAILABLE_EXAMPLE_FILE_PATH"
VHOST_AVAILABLE_DOMAIN_FILE_PATH="$VHOST_AVAILABLE_DOMAIN_FILE_PATH"
VHOST_AVAILABLE_DOMAIN_LETSENCRYPT_FILE_PATH="$VHOST_AVAILABLE_DOMAIN_LETSENCRYPT_FILE_PATH"
VHOST_AVAILABLE_DOMAIN_SELFCERT_FILE_PATH="$VHOST_AVAILABLE_DOMAIN_SELFCERT_FILE_PATH"
VHOST_ENABLED_EXAMPLE_FILE_PATH="$VHOST_ENABLED_EXAMPLE_FILE_PATH"
VHOST_ENABLED_DOMAIN_FILE_PATH="$VHOST_ENABLED_DOMAIN_FILE_PATH"
VHOST_ENABLED_DOMAIN_LETSENCRYPT_FILE_PATH="$VHOST_ENABLED_DOMAIN_LETSENCRYPT_FILE_PATH"
VHOST_ENABLED_DOMAIN_SELFCERT_FILE_PATH="$VHOST_ENABLED_DOMAIN_SELFCERT_FILE_PATH"

PHP_VERSION="$PHP_VERSION"
PHP_CLI_CONFIG_PATH="$PHP_CLI_CONFIG_PATH"
PHP_CLI_CUSTOM_INI_FILE="$PHP_CLI_CUSTOM_INI_FILE"
PHP_CLI_CUSTOM_INI_PATH="$PHP_CLI_CUSTOM_INI_PATH"

LETSENCRYPT_PATH="$LETSENCRYPT_PATH"
LETSENCRYPT_DOMAIN_PATH="$LETSENCRYPT_DOMAIN_PATH"

SELFCERT_PATH="$SELFCERT_PATH"
SELFCERT_DOMAIN_PATH="$SELFCERT_DOMAIN_PATH"

CRON_FILE="$CRON_BLUEGREEN_DEPLOY_FILE"
EOF

# Check if the .env file was created successfully
if [[ ! -f "$ENV_FILE" ]]; then
    echo "🟥  Failed to create .env file. Aborting."
    exit 1
else
    echo "✅  Environment file created at $ENV_FILE"
fi
